name: Build Lucide XAML

on:
  push:
    tags:
      - '*'

jobs:
  icons-build:
    runs-on: ubuntu-latest
    container:
      image: node:23
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build with pnpm
        run: |
          npm install -g pnpm
          cd lucide
          pnpm install
          pnpm run build:outline-icons
          pnpm run build:font
          cd ..
          node ./gen-codepoints.js

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lucide-build
          path: |
            lucide/lucide-font
            src/LucideIcons/Resources

  dotnet-build:
    needs: icons-build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:9.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: lucide-build
          path: .

      - name: Build and pack all projects in src with tag version
        run: |
          VERSION="${GITHUB_REF##*/}"
          find ./src -name '*.csproj' | while read csproj; do
            dotnet pack "$csproj" -c Release -o ./nupkgs /p:PackageVersion="$VERSION"
          done

      - name: Push all nupkg to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          for pkg in ./nupkgs/*.nupkg; do
            dotnet nuget push "$pkg" -k "$NUGET_API_KEY" -s https://api.nuget.org/v3/index.json --skip-duplicate
          done
